# services:
#   # Backend service
#   - type: web
#     name: paint-online-back
#     env: node
#     buildCommand: cd server && npm install
#     startCommand: cd server && node index.js
#     envVars:
#       - key: NODE_ENV
#         value: production

#   # Frontend service (Static Site)
#   - type: web
#     name: paint-online-front
#     env: static
#     buildCommand: cd client && npm install && npm run build
#     staticPublishPath: ./client/build
#     routes:
#       - type: rewrite
#         source: /*
#         destination: /index.html
